version: "3.8"

services:
  serverdashboard:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: serverdashboard
    restart: unless-stopped
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - CONFIG_DIR=/app/data
      - PORT=3232
    volumes:
      - serverdashboard_data:/app/data

volumes:
  serverdashboard_data:
