version: "3.8"

services:
  serverdashboard:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: serverdashboard
    restart: unless-stopped
    ports:
      - "3232:3232"
    environment:
      - NODE_ENV=production
      - CONFIG_DIR=/app/data   # komt overeen met server.js
      - PORT=3232              # server luistert hierop
    volumes:
      - ./data:/app/data       # hostmap voor config & data (containers.config.json)
